### ISSUE TITLE
[FEAT]: Get Market Info

### ISSUE THREAD

**Issue by uhyunglee** [uhyunglee/crypto-service#1]
## 🚀이슈 제목
Get Market Info

## 📝이슈 설명
업비트 마켓정보 가져오기 

## ✨작업 내용
- [ ] 
- [ ] 
- [ ] 

## ☑️To-Do

- [ ] 아키텍처 생성
- [ ] 마켓 엔티티 생성
- [ ] 마켓 Dto 생성
- [ ] 마켓 컨트롤러 생성
- [ ] 마켓 서비스 생성
- [ ]
